### ISSUE TITLE
Strange log tailing failure causing entire WebUI to crash.

### ISSUE THREAD

**Issue by ciak2009** [hexparrot/mineos-node#173]
```bash
Tail error:Error: EMFILE: too many open files, open '/home/minecraft/servers/Realm of Mianite Testing/logs/latest.log'
Tail error:Error: EMFILE: too many open files, open '/home/minecraft/servers/Realm of Mianite Testing/logs/latest.log'
Tail error:Error: EMFILE: too many open files, open '/home/minecraft/servers/Realm of Mianite Testing/logs/latest.log'
Tail error:Error: EMFILE: too many open files, open '/home/minecraft/servers/Realm of Mianite Testing/logs/latest.log'
Tail error:Error: EMFILE: too many open files, open '/home/minecraft/servers/Realm of Mianite Testing/logs/latest.log'
Tail error:Error: EMFILE: too many open files, open '/home/minecraft/servers/Realm of Mianite Testing/logs/latest.log'
Tail error:Error: EMFILE: too many open files, open '/home/minecraft/servers/Realm of Mianite Testing/logs/latest.log'
Tail error:Error: EMFILE: too many open files, open '/home/minecraft/servers/Realm of Mianite Testing/logs/latest.log'
Tail error:Error: EMFILE: too many open files, open '/home/minecraft/servers/Realm of Mianite Testing/logs/latest.log'
Tail error:Error: EMFILE: too many open files, open '/home/minecraft/servers/Realm of Mianite Testing/logs/latest.log'
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at addListener (events.js:252:17)
    at once (events.js:278:8)
    at Transport.logException (/usr/games/minecraft/node_modules/winston/lib/winston/transports/transport.js:133:8)
    at logAndWait (/usr/games/minecraft/node_modules/winston/lib/winston/logger.js:646:15)
    at /usr/games/minecraft/node_modules/winston/node_modules/async/lib/async.js:157:13
    at _each (/usr/games/minecraft/node_modules/winston/node_modules/async/lib/async.js:57:9)
    at Object.async.each (/usr/games/minecraft/node_modules/winston/node_modules/async/lib/async.js:156:9)
    at Logger._uncaughtException (/usr/games/minecraft/node_modules/winston/lib/winston/logger.js:669:9)
    at emitOne (events.js:90:13)
    at process.emit (events.js:182:7)
Tail error:Error: EMFILE: too many open files, open '/home/minecraft/servers/Realm of Mianite Testing/logs/latest.log'
(node) warning: possible EventEmitter memory leak detected. 11 logged listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at addListener (events.js:252:17)
    at once (events.js:278:8)
    at Transport.logException (/usr/games/minecraft/node_modules/winston/lib/winston/transports/transport.js:132:8)
    at logAndWait (/usr/games/minecraft/node_modules/winston/lib/winston/logger.js:646:15)
    at /usr/games/minecraft/node_modules/winston/node_modules/async/lib/async.js:157:13
    at _each (/usr/games/minecraft/node_modules/winston/node_modules/async/lib/async.js:57:9)
    at Object.async.each (/usr/games/minecraft/node_modules/winston/node_modules/async/lib/async.js:156:9)
    at Logger._uncaughtException (/usr/games/minecraft/node_modules/winston/lib/winston/logger.js:669:9)
    at emitOne (events.js:90:13)
    at process.emit (events.js:182:7)
Tail error:Error: EMFILE: too many open files, open '/home/minecraft/servers/Realm of Mianite Testing/logs/latest.log'
Tail error:Error: EMFILE: too many open files, open '/home/minecraft/servers/Realm of Mianite Testing/logs/latest.log'
Tail error:Error: EMFILE: too many open files, open '/home/minecraft/servers/Realm of Mianite Testing/logs/latest.log'
Tail error:Error: EMFILE: too many open files, open '/home/minecraft/servers/Realm of Mianite Testing/logs/latest.log'
Tail error:Error: EMFILE: too many open files, open '/home/minecraft/servers/Realm of Mianite Testing/logs/latest.log'
Tail error:Error: EMFILE: too many open files, open '/home/minecraft/servers/Realm of Mianite Testing/logs/latest.log'
Tail error:Error: EMFILE: too many open files, open '/home/minecraft/servers/Realm of Mianite Testing/logs/latest.log'
Tail error:Error: EMFILE: too many open files, open '/home/minecraft/servers/Realm of Mianite Testing/logs/latest.log'
Tail error:Error: EMFILE: too many open files, open '/home/minecraft/servers/Realm of Mianite Testing/logs/latest.log'
Tail error:Error: EMFILE: too many open files, open '/home/minecraft/servers/Realm of Mianite Testing/logs/latest.log'
Tail error:Error: EMFILE: too many open files, open '/home/minecraft/servers/Realm of Mianite Testing/logs/latest.log'
Tail error:Error: EMFILE: too many open files, open '/home/minecraft/servers/Realm of Mianite Testing/logs/latest.log'
```

As always, thanks!

**Comment by hexparrot** [comment]
Are you symlinking `/var/games/minecraft` out to your home directory?  Are there recursive symlinks somewhere in your logs?

Also, it can't tell if the server is running because you're using spaces in the server name.  Spaces can't be handled properly by the `screen` instance, so MineOS is looking for the `screen` instance "mc-Realm of Mianite Testing" but the instance that is being created is "mc-Realm"

Spaces == no go in server names.

**Comment by ciak2009** [comment]
> Spaces == no go in server names.

that was the answer to my question, a clean install seems to have resolved the other issue :)

**Comment by ciak2009** [comment]
This issue has returned, the spaces fixed that one, but I am still having this WebUI crash regarding too many open files, the only symlink I'm using is for the archives directory

**Comment by hexparrot** [comment]
Can you identify the directories specifically that have too many files?  My best guess is its on the order of several thousand.  If I know which directories, I might be able to determine which parts of MineOS is overreaching.  What are the contents of your log directory (file counts, file sizes) if possible.

**Comment by ciak2009** [comment]
It seems like its related to latest.log, but this is a clean server, not my typical million file setup :) I did update to Node 5.8 and so far I think that may have helped, not sure though

**Comment by hexparrot** [comment]
What server software are you using (minecraft)?
