### ISSUE TITLE
mineos_console.js -V throws error unless server is specified

### ISSUE THREAD

**Issue by Nick2253** [hexparrot/mineos-node#285]
You cannot use `mineos_console.js -V` (or `--version`) to get the version of  MineOS unless you specify a server using `-s` or `--server_name=`.

```
# ./mineos_console.js -V
path.js:8
    throw new TypeError('Path must be a string. Received ' +
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.posix.join (path.js:818:5)
    at new mineos.mc (/usr/games/minecraft/mineos.js:133:15)
    at Object.<anonymous> (/usr/games/minecraft/mineos_console.js:119:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
```

**Comment by hexparrot** [comment]
Sorry for the delay; resolved this just now in b68925b348c505512692acd61255ae26ce7d9eb3

`-s` and servername no longer required for checking version. Thanks for the issue raising!
