### ISSUE TITLE
webUI frozen and forces relogin upon page refresh

### ISSUE THREAD

**Issue by Xplodin** [hexparrot/mineos-node#297]
I have done everything i can to update, reset, etc for the webui.

cant get it to let me stay logged in longer than 5 seconds before freezing and making me log in again when i refresh the page. I have 5 servers I cannot lose or delete that were working fine before system reboot maintenance. Now everything isnt working correctly.

Also no profiles show up and the log shows this:

l":"info","message":"Starting up server, using commit: b28c5be fw.ignore for all skip_dirs\n","timestamp":"2019-08-23T00:47:32.958Z"}
{"level":"info","message":"[WEBUI] New file found in import directory /var/games/minecraft/import/Enigmatica2Server-1.70.zip","timestamp":"2019-08-23T00:47:33.317Z"}
{"level":"info","message":"[WEBUI] New file found in import directory /var/games/minecraft/import/FTBPresentsStoneblock2Server_1.15.0 - Copy.zip","timestamp":"2019-08-23T00:47:33.318Z"}
{"level":"info","message":"[WEBUI] New file found in import directory /var/games/minecraft/import/PO3-3.0.41-SERVER.zip","timestamp":"2019-08-23T00:47:33.319Z"}
{"level":"info","message":"[PO3] eula.txt detected: ACCEPTED (eula=true)","timestamp":"2019-08-23T00:47:34.824Z"}
{"level":"info","message":"[Vanillabean] eula.txt detected: ACCEPTED (eula=true)","timestamp":"2019-08-23T00:47:34.824Z"}
{"level":"info","message":"[beanmatica2] eula.txt detected: ACCEPTED (eula=true)","timestamp":"2019-08-23T00:47:34.825Z"}
{"level":"info","message":"[lobby] eula.txt detected: ACCEPTED (eula=true)","timestamp":"2019-08-23T00:47:34.825Z"}
{"level":"info","message":"[stonebean2] eula.txt detected: ACCEPTED (eula=true)","timestamp":"2019-08-23T00:47:34.826Z"}
{"level":"info","message":"[Beangeecord] autostart = false","timestamp":"2019-08-23T00:47:38.000Z"}
{"level":"error","message":"[Beangeecord] Aborted server startup; condition not met: true","timestamp":"2019-08-23T00:47:38.002Z"}
{"level":"info","message":"[PO3] autostart = false","timestamp":"2019-08-23T00:47:38.048Z"}
{"level":"error","message":"[PO3] Aborted server startup; condition not met: true","timestamp":"2019-08-23T00:47:38.049Z"}
{"level":"info","message":"[Vanillabean] autostart = false","timestamp":"2019-08-23T00:47:38.052Z"}
{"level":"error","message":"[Vanillabean] Aborted server startup; condition not met: true","timestamp":"2019-08-23T00:47:38.052Z"}
{"level":"info","message":"[beanmatica2] autostart = false","timestamp":"2019-08-23T00:47:38.053Z"}
{"level":"error","message":"[beanmatica2] Aborted server startup; condition not met: true","timestamp":"2019-08-23T00:47:38.054Z"}
{"level":"info","message":"[lobby] autostart = false","timestamp":"2019-08-23T00:47:38.055Z"}
{"level":"error","message":"[lobby] Aborted server startup; condition not met: true","timestamp":"2019-08-23T00:47:38.056Z"}
{"level":"info","message":"[stonebean2] autostart = false","timestamp":"2019-08-23T00:47:38.057Z"}
{"level":"error","message":"[stonebean2] Aborted server startup; condition not met: true","timestamp":"2019-08-23T00:47:38.058Z"}
{"date":"Fri Aug 23 2019 02:47:54 GMT+0200 (Central European Summer Time)","process":{"pid":24139,"uid":0,"gid":0,"cwd":"/usr/games/minecraft","execPath":"/usr/bin/node","version":"v10.15.2","argv":["/usr/bin/node","/usr/games/minecraft/webui.js"],"memoryUsage":{"rss":217468928,"heapTotal":136851456,"heapUsed":90040648,"external":4062143}},"os":{"loadavg":[1.087890625,0.837890625,0.5625],"uptime":57518},"trace":[{"column":15,"file":"internal/modules/cjs/loader.js","function":"Module._resolveFilename","line":581,"method":"_resolveFilename","native":false},{"column":25,"file":"internal/modules/cjs/loader.js","function":"Module._load","line":507,"method":"_load","native":false},{"column":17,"file":"internal/modules/cjs/loader.js","function":"Module.require","line":637,"method":"require","native":false},{"column":18,"file":"internal/modules/cjs/helpers.js","function":"require","line":22,"method":null,"native":false},{"column":19,"file":"/usr/games/minecraft/node_modules/userid/lib/userid.js","function":null,"line":5,"method":null,"native":false},{"column":30,"file":"internal/modules/cjs/loader.js","function":"Module._compile","line":689,"method":"_compile","native":false},{"column":10,"file":"internal/modules/cjs/loader.js","function":"Module._extensions..js","line":700,"method":".js","native":false},{"column":32,"file":"internal/modules/cjs/loader.js","function":"Module.load","line":599,"method":"load","native":false},{"column":12,"file":"internal/modules/cjs/loader.js","function":"tryModuleLoad","line":538,"method":null,"native":false},{"column":3,"file":"internal/modules/cjs/loader.js","function":"Module._load","line":530,"method":"_load","native":false}],"stack":["Error: Cannot find module '/usr/games/minecraft/node_modules/userid/build/Debug/userid.node'","    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)","    at Function.Module._load (internal/modules/cjs/loader.js:507:25)","    at Module.require (internal/modules/cjs/loader.js:637:17)","    at require (internal/modules/cjs/helpers.js:22:18)","    at Object.<anonymous> (/usr/games/minecraft/node_modules/userid/lib/userid.js:5:19)","    at Module._compile (internal/modules/cjs/loader.js:689:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)","    at Module.load (internal/modules/cjs/loader.js:599:32)","    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)","    at Function.Module._load (internal/modules/cjs/loader.js:530:3)"],"level":"error","message":"uncaughtException: Cannot find module '/usr/games/minecraft/node_modules/userid/build/Debug/userid.node'","timestamp":"2019-08-23T00:47:54.932Z"}
{"level":"info","message":"[Beangeecord] Discovered server","timestamp":"2019-08-23T00:47:59.858Z"}
{"level":"info","message":"[Beangeecord] Created tail on logs/latest.log","timestamp":"2019-08-23T00:47:59.862Z"}
{"level":"error","message":"[Beangeecord] Create tail on server.log failed","timestamp":"2019-08-23T00:47:59.863Z"}
{"level":"info","message":"[Beangeecord] Watching for file generation: server.log","timestamp":"2019-08-23T00:47:59.863Z"}
{"level":"error","message":"[Beangeecord] Create tail on proxy.log.0 failed","timestamp":"2019-08-23T00:47:59.879Z"}
{"level":"info","message":"[Beangeecord] Watching for file generation: proxy.log.0","timestamp":"2019-08-23T00:47:59.880Z"}
{"level":"error","message":"[Beangeecord] Create tail on logs/fml-server-latest.log failed","timestamp":"2019-08-23T00:47:59.883Z"}
{"level":"info","message":"[Beangeecord] Watching for file generation: logs/fml-server-latest.log","timestamp":"2019-08-23T00:47:59.883Z"}
{"level":"info","message":"[Beangeecord] Using skipDirEntryPatterns: modules,plugins,world,world_the_end,world_nether,dynmap,web,region,playerdata,stats,data","timestamp":"2019-08-23T00:47:59.884Z"}
{"level":"info","message":"[PO3] Discovered server","timestamp":"2019-08-23T00:47:59.914Z"}
{"level":"info","message":"[PO3] Created tail on logs/latest.log","timestamp":"2019-08-23T00:47:59.915Z"}
{"level":"error","message":"[PO3] Create tail on server.log failed","timestamp":"2019-08-23T00:47:59.915Z"}
{"level":"info","message":"[PO3] Watching for file generation: server.log","timestamp":"2019-08-23T00:47:59.915Z"}
{"level":"error","message":"[PO3] Create tail on proxy.log.0 failed","timestamp":"2019-08-23T00:47:59.916Z"}
{"level":"info","message":"[PO3] Watching for file generation: proxy.log.0","timestamp":"2019-08-23T00:47:59.916Z"}
{"level":"error","message":"[PO3] Create tail on logs/fml-server-latest.log failed","timestamp":"2019-08-23T00:47:59.916Z"}
{"level":"info","message":"[PO3] Watching for file generation: logs/fml-server-latest.log","timestamp":"2019-08-23T00:47:59.916Z"}
{"level":"info","message":"[PO3] Using skipDirEntryPatterns: .mixin.out,astralsorcery,backups,config,crash-reports,journeymap,libraries,local,luckperms,mods,mods-resourcepacks,resourcepacks,resources,scripts,woot,world,world_the_end,world_nether,dynmap,plugins,web,region,playerdata,stats,data","timestamp":"2019-08-23T00:47:59.917Z"}
{"level":"info","message":"[Vanillabean] Discovered server","timestamp":"2019-08-23T00:47:59.918Z"}
{"level":"info","message":"[Vanillabean] Created tail on logs/latest.log","timestamp":"2019-08-23T00:47:59.918Z"}
{"level":"error","message":"[Vanillabean] Create tail on server.log failed","timestamp":"2019-08-23T00:47:59.919Z"}
{"level":"info","message":"[Vanillabean] Watching for file generation: server.log","timestamp":"2019-08-23T00:47:59.919Z"}
{"level":"error","message":"[Vanillabean] Create tail on proxy.log.0 failed","timestamp":"2019-08-23T00:47:59.919Z"}
{"level":"info","message":"[Vanillabean] Watching for file generation: proxy.log.0","timestamp":"2019-08-23T00:47:59.919Z"}
{"level":"error","message":"[Vanillabean] Create tail on logs/fml-server-latest.log failed","timestamp":"2019-08-23T00:47:59.920Z"}
{"level":"info","message":"[Vanillabean] Watching for file generation: logs/fml-server-latest.log","timestamp":"2019-08-23T00:47:59.920Z"}
{"level":"info","message":"[Vanillabean] Using skipDirEntryPatterns: plugins,world,world_nether,world_the_end,dynmap,web,region,playerdata,stats,data","timestamp":"2019-08-23T00:47:59.921Z"}
{"level":"info","message":"[beanmatica2] Discovered server","timestamp":"2019-08-23T00:47:59.921Z"}
{"level":"info","message":"[beanmatica2] Created tail on logs/latest.log","timestamp":"2019-08-23T00:47:59.922Z"}
{"level":"error","message":"[beanmatica2] Create tail on server.log failed","timestamp":"2019-08-23T00:47:59.922Z"}
{"level":"info","message":"[beanmatica2] Watching for file generation: server.log","timestamp":"2019-08-23T00:47:59.922Z"}
{"level":"error","message":"[beanmatica2] Create tail on proxy.log.0 failed","timestamp":"2019-08-23T00:47:59.922Z"}
{"level":"info","message":"[beanmatica2] Watching for file generation: proxy.log.0","timestamp":"2019-08-23T00:47:59.923Z"}
{"level":"error","message":"[beanmatica2] Create tail on logs/fml-server-latest.log failed","timestamp":"2019-08-23T00:47:59.923Z"}
{"level":"info","message":"[beanmatica2] Watching for file generation: logs/fml-server-latest.log","timestamp":"2019-08-23T00:47:59.923Z"}
{"level":"info","message":"[beanmatica2] Using skipDirEntryPatterns: .mixin.out,TombManyGraves,astralsorcery,backups,config,crash-reports,journeymap,libraries,local,luckperms,mods,nucleus,patchouli_books,schematics,scripts,structures,structurize,world,world_the_end,world_nether,dynmap,plugins,web,region,playerdata,stats,data","timestamp":"2019-08-23T00:47:59.924Z"}
{"level":"info","message":"[lobby] Discovered server","timestamp":"2019-08-23T00:47:59.925Z"}
{"level":"info","message":"[lobby] Created tail on logs/latest.log","timestamp":"2019-08-23T00:47:59.925Z"}
{"level":"error","message":"[lobby] Create tail on server.log failed","timestamp":"2019-08-23T00:47:59.925Z"}
{"level":"info","message":"[lobby] Watching for file generation: server.log","timestamp":"2019-08-23T00:47:59.925Z"}
{"level":"error","message":"[lobby] Create tail on proxy.log.0 failed","timestamp":"2019-08-23T00:47:59.926Z"}
{"level":"info","message":"[lobby] Watching for file generation: proxy.log.0","timestamp":"2019-08-23T00:47:59.926Z"}
{"level":"error","message":"[lobby] Create tail on logs/fml-server-latest.log failed","timestamp":"2019-08-23T00:47:59.926Z"}
{"level":"info","message":"[lobby] Watching for file generation: logs/fml-server-latest.log","timestamp":"2019-08-23T00:47:59.927Z"}
{"level":"info","message":"[lobby] Using skipDirEntryPatterns: cache,plugins,world,world_nether,world_the_end,dynmap,web,region,playerdata,stats,data","timestamp":"2019-08-23T00:47:59.927Z"}
{"level":"info","message":"[stonebean2] Discovered server","timestamp":"2019-08-23T00:47:59.928Z"}
{"level":"info","message":"[stonebean2] Created tail on logs/latest.log","timestamp":"2019-08-23T00:47:59.928Z"}
{"level":"error","message":"[stonebean2] Create tail on server.log failed","timestamp":"2019-08-23T00:47:59.928Z"}
{"level":"info","message":"[stonebean2] Watching for file generation: server.log","timestamp":"2019-08-23T00:47:59.929Z"}
{"level":"error","message":"[stonebean2] Create tail on proxy.log.0 failed","timestamp":"2019-08-23T00:47:59.929Z"}
{"level":"info","message":"[stonebean2] Watching for file generation: proxy.log.0","timestamp":"2019-08-23T00:47:59.929Z"}
{"level":"error","message":"[stonebean2] Create tail on logs/fml-server-latest.log failed","timestamp":"2019-08-23T00:47:59.929Z"}
{"level":"info","message":"[stonebean2] Watching for file generation: logs/fml-server-latest.log","timestamp":"2019-08-23T00:47:59.930Z"}
{"level":"info","message":"[stonebean2] Using skipDirEntryPatterns: .mixin.out,backups,config,crash-reports,libraries,llibrary,local,luckperms,mods,nucleus,scripts,snapshots-server,world,world_the_end,world_nether,dynmap,plugins,web,region,playerdata,stats,data","timestamp":"2019-08-23T00:47:59.930Z"}
{"level":"info","message":"Starting up server, using commit: b28c5be fw.ignore for all skip_dirs\n","timestamp":"2019-08-23T00:48:00.005Z"}
{"level":"info","message":"[WEBUI] New file found in import directory /var/games/minecraft/import/Enigmatica2Server-1.70.zip","timestamp":"2019-08-23T00:48:00.357Z"}
{"level":"info","message":"[WEBUI] New file found in import directory /var/games/minecraft/import/FTBPresentsStoneblock2Server_1.15.0 - Copy.zip","timestamp":"2019-08-23T00:48:00.358Z"}
{"level":"info","message":"[WEBUI] New file found in import directory /var/games/minecraft/import/PO3-3.0.41-SERVER.zip","timestamp":"2019-08-23T00:48:00.358Z"}
{"level":"info","message":"[PO3] eula.txt detected: ACCEPTED (eula=true)","timestamp":"2019-08-23T00:48:01.881Z"}
{"level":"info","message":"[Vanillabean] eula.txt detected: ACCEPTED (eula=true)","timestamp":"2019-08-23T00:48:01.882Z"}
{"level":"info","message":"[beanmatica2] eula.txt detected: ACCEPTED (eula=true)","timestamp":"2019-08-23T00:48:01.882Z"}
{"level":"info","message":"[lobby] eula.txt detected: ACCEPTED (eula=true)","timestamp":"2019-08-23T00:48:01.883Z"}
{"level":"info","message":"[stonebean2] eula.txt detected: ACCEPTED (eula=true)","timestamp":"2019-08-23T00:48:01.883Z"}
{"level":"info","message":"[Beangeecord] autostart = false","timestamp":"2019-08-23T00:48:05.016Z"}
{"level":"error","message":"[Beangeecord] Aborted server startup; condition not met: true","timestamp":"2019-08-23T00:48:05.018Z"}
{"level":"info","message":"[PO3] autostart = false","timestamp":"2019-08-23T00:48:05.082Z"}
{"level":"error","message":"[PO3] Aborted server startup; condition not met: true","timestamp":"2019-08-23T00:48:05.085Z"}
{"level":"info","message":"[Vanillabean] autostart = false","timestamp":"2019-08-23T00:48:05.102Z"}
{"level":"error","message":"[Vanillabean] Aborted server startup; condition not met: true","timestamp":"2019-08-23T00:48:05.104Z"}
{"level":"info","message":"[beanmatica2] autostart = false","timestamp":"2019-08-23T00:48:05.107Z"}
{"level":"error","message":"[beanmatica2] Aborted server startup; condition not met: true","timestamp":"2019-08-23T00:48:05.108Z"}
{"level":"info","message":"[lobby] autostart = false","timestamp":"2019-08-23T00:48:05.111Z"}
{"level":"error","message":"[lobby] Aborted server startup; condition not met: true","timestamp":"2019-08-23T00:48:05.113Z"}
{"level":"info","message":"[stonebean2] autostart = false","timestamp":"2019-08-23T00:48:05.116Z"}
{"level":"error","message":"[stonebean2] Aborted server startup; condition not met: true","timestamp":"2019-08-23T00:48:05.118Z"}
{"level":"info","message":"[PO3] committing world to disk every 60 minutes.","timestamp":"2019-08-23T00:48:59.919Z"}
{"level":"info","message":"[beanmatica2] committing world to disk every 60 minutes.","timestamp":"2019-08-23T00:48:59.932Z"}

I have no idea whats going on

**Comment by Xplodin** [comment]
no idea how i fixed it but its working
