### ISSUE TITLE
Getting error "No profiles are available; check internet connectivity and refresh the profile list."

### ISSUE THREAD

**Issue by bluasoar** [hexparrot/mineos-node#363]
I Re-installed mineos-node and on the Profiles tab had the following error " No profiles are available; check internet connectivity and refresh the profile list." 

I did some research and found out that updating the WebUI could solve this but I have had no success after following these instructions http://minecraft.codeemo.com/mineoswiki/index.php?title=Updating_the_Webui the error is still there. 

I am running unRAID 6.8.3 and Mineos-node is being run in container. Any help would be appreciated. 

Thank you!

**Comment by Ahze85283** [comment]
I get a similar issue from time to time 
it's due to the way unraids permissions work

You might need to Chown/chgrp all the /var & /mnt files

**Comment by bluasoar** [comment]
> 
> 
> I get a similar issue from time to time
> it's due to the way unraids permissions work
> 
> You might need to Chown/chgrp all the /var & /mnt files

No luck though i'm not sure I ran the commands correctly (dont use CLI often and am fairly new to linux), I docker execd into the mineos container and switched the ownership over to the default user nobody and users group. running chown 99:100 /var/* and /mnt/* as well as /usr/*.

**Comment by bluasoar** [comment]
Well I give up i've been trying to solve this issue for hours with no success. I'm sure it's something insanely simple but I've had the profiles load and then just completely lock up and mineos needs a reboot and then the profiles no longer load. Not too sure what could have caused this. I have had mineos installed on the exact same system with servers running... Kinda odd.

**Comment by bluasoar** [comment]
After some more tinkering I am getting the following error 
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Linux 4.19.107-Unraid
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/node_modules/posix
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! posix@4.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the posix@4.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-03T01_51_19_362Z-debug.log

**Comment by TheGuyWhoCodes** [comment]
+1 on this issue, will try doing a chown on /var

**Comment by Ahze85283** [comment]
The only time you really need to chown any of the directories is after the mover moves from cache to drives. In my experience that's what messes up the permissions because the user and the group doesn't exist within unraid now if we can get the 'mc' UID and GID to match 90 / 100 then I believe this can resolve the whole issue (instead of 1000/1000)

**Comment by bluasoar** [comment]
Anyone know how I can solve this issue? Any help would be appreciated..

**Comment by HameedSilvertoe** [comment]
I'm getting the "No profiles are available; check internet connectivity and refresh the profile list." as well. I cannot view Spigot profile/jars either. I have the latest Git commit (4c1b43a). Would the latest commit have changed something that would cause this? Nothing else in my configuration has changed and I was able to view items in both Profiles and Spigot and update my servers previously.
