### ISSUE TITLE
"_LIBCPP_TRIVIAL_PAIR_COPY_CTOR" is no longer supported

### ISSUE THREAD

**Issue by jagdtigger** [hexparrot/mineos-node#403]
Hi all!

So i am installing mineos in a truenas jail, the wili is outdated but i managed to find the correct package names. But when i run 'echo "CXX=c++ npm install userid" | sh' it errors out:
`root@mine-os:/usr/local/games/minecraft # echo "CXX=c++ npm install userid" | sh

> posix@4.2.0 install /usr/local/games/minecraft/node_modules/posix
> node-gyp rebuild

gmake: Entering directory '/usr/local/games/minecraft/node_modules/posix/build'
  CXX(target) Release/obj.target/posix/src/posix.o
In file included from ../src/posix.cc:1:
In file included from ../../nan/nan.h:53:
In file included from /root/.cache/node-gyp/10.24.1/include/node/uv.h:52:
In file included from /root/.cache/node-gyp/10.24.1/include/node/uv/errno.h:25:
In file included from /usr/include/c++/v1/errno.h:25:
/usr/include/c++/v1/__config:122:2: error: "_LIBCPP_TRIVIAL_PAIR_COPY_CTOR" is no longer supported. use
      _LIBCPP_DEPRECATED_ABI_DISABLE_PAIR_TRIVIAL_COPY_CTOR instead
#error "_LIBCPP_TRIVIAL_PAIR_COPY_CTOR" is no longer supported. \
 ^
1 error generated.
gmake: *** [posix.target.mk:105: Release/obj.target/posix/src/posix.o] Error 1
gmake: Leaving directory '/usr/local/games/minecraft/node_modules/posix/build'
gyp ERR! build error 
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System FreeBSD 12.2-RELEASE-p6
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/games/minecraft/node_modules/posix
gyp ERR! node -v v10.24.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! posix@4.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the posix@4.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-05-01T08_25_56_671Z-debug.log
`
Tried it on release 11.4 and 12.2...

**Comment by jsegaert** [comment]
Did you try [this procedure](https://www.truenas.com/community/threads/how-to-install-mineos-node-in-a-jail-alternative-to-using-the-mineos-plugin.44686/)?  It's using  patched version of node-userid.  I keep this up-to-date for FreeNAS/TrueNAS.

**Comment by jagdtigger** [comment]
Tried, console output:
```
root@mineos-jail:/ # mkdir -p /usr/compat/linux/proc
root@mineos-jail:/ # mkdir -p /usr/local/games
root@mineos-jail:/ # cd /usr/local/games
root@mineos-jail:/usr/local/games # git clone git://github.com/hexparrot/mineos-node minecraft
Cloning into 'minecraft'...
remote: Enumerating objects: 6003, done.
remote: Counting objects: 100% (47/47), done.
remote: Compressing objects: 100% (43/43), done.
remote: Total 6003 (delta 24), reused 8 (delta 4), pack-reused 5956
Receiving objects: 100% (6003/6003), 5.14 MiB | 5.77 MiB/s, done.
Resolving deltas: 100% (3537/3537), done.
root@mineos-jail:/usr/local/games # cd minecraft
root@mineos-jail:/usr/local/games/minecraft # chmod +x *.sh
root@mineos-jail:/usr/local/games/minecraft # ./generate-sslcert.sh
Generating a RSA private key
........................................+++++
.....................................+++++
writing new private key to '.tmpkey.pem'
-----
writing RSA key
root@mineos-jail:/usr/local/games/minecraft # cp mineos.conf /etc/mineos.conf
root@mineos-jail:/usr/local/games/minecraft # npm install jsegaert/node-userid

> posix@4.2.0 install /usr/local/games/minecraft/node_modules/posix
> node-gyp rebuild

gmake: Entering directory '/usr/local/games/minecraft/node_modules/posix/build'
  CXX(target) Release/obj.target/posix/src/posix.o
In file included from ../src/posix.cc:1:
In file included from ../../nan/nan.h:2884:
../../nan/nan_typedarray_contents.h:34:43: warning: 'GetContents' is deprecated: Use GetBackingStore. See http://crbug.com/v8/9908.
      [-Wdeprecated-declarations]
      data   = static_cast<char*>(buffer->GetContents().Data()) + byte_offset;
                                          ^
/root/.cache/node-gyp/15.14.0/include/node/v8.h:5317:3: note: 'GetContents' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use GetBackingStore. See http://crbug.com/v8/9908.")
  ^
/root/.cache/node-gyp/15.14.0/include/node/v8config.h:402:39: note: expanded from macro 'V8_DEPRECATE_SOON'
# define V8_DEPRECATE_SOON(message) [[deprecated(message)]]
                                      ^
1 warning generated.
  SOLINK_MODULE(target) Release/obj.target/posix.node
  COPY Release/posix.node
gmake: Leaving directory '/usr/local/games/minecraft/node_modules/posix/build'

> userid@1.0.0-beta.6 install /usr/local/games/minecraft/node_modules/userid
> npm run build


> userid@1.0.0-beta.6 build /usr/local/games/minecraft/node_modules/userid
> node-gyp rebuild

gmake: Entering directory '/usr/local/games/minecraft/node_modules/userid/build'
  CC(target) Release/obj.target/nothing/../node-addon-api/src/nothing.o
  AR(target) Release/obj.target/../node-addon-api/src/nothing.a
  COPY Release/nothing.a
  CXX(target) Release/obj.target/userid/src/Gid.o
../src/Gid.cc:60:18: warning: object backing the pointer will be destroyed at the end of the full-expression [-Wdangling-gsl]
  auto utfname = std::string(info[0].As<String>()).c_str();
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
  CXX(target) Release/obj.target/userid/src/Gids.o
../src/Gids.cc:83:19: warning: object backing the pointer will be destroyed at the end of the full-expression [-Wdangling-gsl]
  auto username = std::string(info[0].As<String>()).c_str();
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
  CXX(target) Release/obj.target/userid/src/GroupName.o
  CXX(target) Release/obj.target/userid/src/Ids.o
../src/Ids.cc:52:18: warning: object backing the pointer will be destroyed at the end of the full-expression [-Wdangling-gsl]
  auto utfname = std::string(info[0].As<String>()).c_str();
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
  CXX(target) Release/obj.target/userid/src/userid.o
  CXX(target) Release/obj.target/userid/src/UserName.o
  SOLINK_MODULE(target) Release/obj.target/userid.node
  COPY Release/userid.node
gmake: Leaving directory '/usr/local/games/minecraft/node_modules/userid/build'
+ userid@1.0.0-beta.6
added 571 packages from 481 contributors and audited 575 packages in 24.056s
found 32 vulnerabilities (9 low, 5 moderate, 18 high)
  run `npm audit fix` to fix them, or `npm audit` for details
root@mineos-jail:/usr/local/games/minecraft # echo "CXX=c++ npm install" | sh
audited 575 packages in 2.8s
found 32 vulnerabilities (9 low, 5 moderate, 18 high)
  run `npm audit fix` to fix them, or `npm audit` for details
root@mineos-jail:/usr/local/games/minecraft # adduser minecraft
Username: ^C
root@mineos-jail:/usr/local/games/minecraft # adduser
Username: minecraft
Full name: 
Uid (Leave empty for default): 1006
Login group [minecraft]: ^C
root@mineos-jail:/usr/local/games/minecraft # adduser
Username: mcserver
Full name: 
Uid (Leave empty for default): 1006
Login group [mcserver]: 
Login group is mcserver. Invite mcserver into other groups? []: games
Login class [default]: 
Shell (sh csh tcsh git-shell bash rbash nologin) [sh]: bash
Home directory [/home/mcserver]: 
Home directory permissions (Leave empty for default): 
Use password-based authentication? [yes]: 
Use an empty password? (yes/no) [no]: 
Use a random password? (yes/no) [no]: 
Enter password: 
Enter password again: 
Lock out the account after creation? [no]: 
Username   : mcserver
Password   : *****
Full Name  : 
Uid        : 1006
Class      : 
Groups     : mcserver games
Home       : /home/mcserver
Home Mode  : 
Shell      : /usr/local/bin/bash
Locked     : no
OK? (yes/no): yes
adduser: INFO: Successfully added (mcserver) to the user database.
Add another user? (yes/no): no
Goodbye!
root@mineos-jail:/usr/local/games/minecraft # cat /usr/local/games/minecraft/init/supervisor_conf.bsd >> /usr/local/etc/supervisord.conf
root@mineos-jail:/usr/local/games/minecraft # sysrc supervisord_enable="YES"
supervisord_enable:  -> YES
root@mineos-jail:/usr/local/games/minecraft # service supervisord start
Starting supervisord.

```
When i try to open webui:
This page isn’t working <mcserver-ip> didn’t send any data.
ERR_EMPTY_RESPONSE

**Comment by jsegaert** [comment]
OK, that got you passed the node-userid error and completed the installation.

Are you connecting using http or https to the MineOS webUI?  How did you set-up your jail's networking... using NAT of DHCP?  If you're using NAT, you need to use the IP address of your host and set up port forwarding for that jail.

**Comment by jagdtigger** [comment]
I was trying http, switching to https brings up the webui. I really appriciate your help! :)
