### ISSUE TITLE
Problems compiling on FreeBSD 12.2

### ISSUE THREAD

**Issue by jzdm** [hexparrot/mineos-node#411]
During installation on FreeBSD 12.2 the following error occurs:

    ╰─ echo "CXX=c++ npm install userid" | sh
    
    > userid@1.0.0-beta.9 install /usr/local/games/minecraft/node_modules/userid
    > npm run build
    
    
    > userid@1.0.0-beta.9 build /usr/local/games/minecraft/node_modules/userid
    > node-gyp rebuild
    
    gmake: Entering directory '/usr/local/games/minecraft/node_modules/userid/build'
      CXX(target) Release/obj.target/userid/src/Gid.o
    In file included from ../src/Gid.cc:4:
    In file included from ../src/userid.hh:4:
    In file included from /usr/local/games/minecraft/node_modules/userid/node_modules/node-addon-api/napi.h:4:
    In file included from /root/.cache/node-gyp/10.24.1/include/node/node_api.h:4:
    In file included from /usr/include/c++/v1/stddef.h:39:
    /usr/include/c++/v1/__config:122:2: error: "_LIBCPP_TRIVIAL_PAIR_COPY_CTOR" is no longer supported. use _LIBCPP_DEPRECATED_ABI_DISABLE_PAIR_TRIVIAL_COPY_CTOR instead
    #error "_LIBCPP_TRIVIAL_PAIR_COPY_CTOR" is no longer supported. \
     ^
    1 error generated.
    gmake: *** [userid.target.mk:106: Release/obj.target/userid/src/Gid.o] Error 1
    gmake: Leaving directory '/usr/local/games/minecraft/node_modules/userid/build'
    gyp ERR! build error
    gyp ERR! stack Error: `gmake` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
    gyp ERR! System FreeBSD 12.2-RELEASE-p6
    gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /usr/local/games/minecraft/node_modules/userid
    gyp ERR! node -v v10.24.1
    gyp ERR! node-gyp -v v5.1.0
    gyp ERR! not ok
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! userid@1.0.0-beta.9 build: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the userid@1.0.0-beta.9 build script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /root/.npm/_logs/2021-06-10T18_32_49_956Z-debug.log
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! userid@1.0.0-beta.9 install: `npm run build`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the userid@1.0.0-beta.9 install script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /root/.npm/_logs/2021-06-10T18_32_50_546Z-debug.log

As suggested in https://github.com/hexparrot/mineos-node/issues/312 I installed and used `npm-node10`.

Do you have any suggestions how to resolve the problem? Thank you.

**Comment by jzdm** [comment]
Following the advice given here https://github.com/hexparrot/mineos-node/issues/403#issuecomment-846796600 did help up to a point.
Also I needed to remove `npm-node10` and instead install `npm` and `node` via `pkg` which are in version

```
$ node -v
v15.14.0
$ npm -v
6.14.8
```
now.

Unfortunately the Web UI is now broken
![CleanShot 2021-06-11 at 09 37 18](https://user-images.githubusercontent.com/2634254/121649223-a78ff000-ca98-11eb-92a7-6fdc2915a571.png)
