### ISSUE TITLE
import server Forge 1.7.10 don't start

### ISSUE THREAD

**Issue by loso2255** [hexparrot/mineos-node#436]
i try to run  "forge-1.7.10-10.13.4.1614-1.7.10-universal.jar" from gui but won't start

so i try to run  the .jar file directly to ssh and this is what i got back:

A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more

i try to delete and copy the two file .jar but nothing same message. 
Any help would be appreciated

**Comment by flareofghast** [comment]
1.7 is pretty old. Maybe you need to downgrade you java? 
On Linux you can run java from extracted files and MineOS has a java_binary server config option not revealed to the GUI. 
You can have OpenJDK or some other java distribution extracted somewhere and set the server config to point to that java binary.

**Comment by loso2255** [comment]
yes, you are right.
i found minecraft 1.7.10 forge need openjdk8
i'm in the docker container right now, i search for other openjk
and it said no other version installed
in the mineOS directly "-bash: update-java-alternatives: command not found".

and when i try to install "openjdk-8-jre":
in docker get istalled 
in the mineOS  "E: Unable to locate package openjdk-8-jre" even i after run "apt-get update"

so i need to download other version of java in zip and decompress that in a certain folder
i don't found how to set you file .jar need to run with this java and other need to run with other java

after i tried with an other version of forge 1.12.2 but same issue with opejdk16
