### ISSUE TITLE
Mineos/nodejs shuts down after error

### ISSUE THREAD

**Issue by scebbers** [hexparrot/mineos-node#473]
Mineos (i.e. the whole nodejs app) shuts down every once in a while after encountering the following error. I tried to track down what causes it but Googling didn't help. I can just start the mineos/nodejs service again and everything works. Can anyone point me in the right direction?

`
{"date":"Mon`` Feb 14 2022 03:01:19 GMT+0100 (Central European Standard Time)","process":{"pid":70191,"uid":0,"gid":0,"cwd":"/","execPath":"/usr/local/bin/node","version":"v14.18.1","argv":["/usr/local/bin/node","/usr/local/games/minecraft/webui.js","start"],"memoryUsage":{"rss":291266560,"heapTotal":216858624,"heapUsed":205047928,"external":4183126,"arrayBuffers":95847}},"os":{"loadavg":[0.67724609375,0.54345703125,0.4794921875],"uptime":4718157},"trace":[{"column":7,"file":"/usr/local/games/minecraft/node_modules/fireworm/lib/file.js","function":null,"line":45,"method":null,"native":false},{"column":5,"file":"fs.js","function":"FSReqCallback.oncomplete","line":192,"method":"oncomplete","native":false}],"stack":["AssertionError [ERR_ASSERTION]: File should always be initialied with stat","    at /usr/local/games/minecraft/node_modules/fireworm/lib/file.js:45:7","    at FSReqCallback.oncomplete (fs.js:192:5)"],"level":"error","message":"uncaughtException: File should always be initialied with stat","timestamp":"2022-02-14T02:01:19.236Z"}
{"date":"Mon Feb 14 2022 03:01:19 GMT+0100 (Central European Standard Time)","process":{"pid":70191,"uid":0,"gid":0,"cwd":"/","execPath":"/usr/local/bin/node","version":"v14.18.1","argv":["/usr/local/bin/node","/usr/local/games/minecraft/webui.js","start"],"memoryUsage":{"rss":291274752,"heapTotal":216858624,"heapUsed":205145944,"external":1725566,"arrayBuffers":95847}},"os":{"loadavg":[0.67724609375,0.54345703125,0.4794921875],"uptime":4718157},"trace":[{"column":7,"file":"/usr/local/games/minecraft/node_modules/fireworm/lib/file.js","function":null,"line":45,"method":null,"native":false},{"column":5,"file":"fs.js","function":"FSReqCallback.oncomplete","line":192,"method":"oncomplete","native":false}],"stack":["AssertionError [ERR_ASSERTION]: File should always be initialied with stat","    at /usr/local/games/minecraft/node_modules/fireworm/lib/file.js:45:7","    at FSReqCallback.oncomplete (fs.js:192:5)"],"level":"error","message":"uncaughtException: File should always be initialied with stat","timestamp":"2022-02-14T02:01:19.237Z"}
`

**Comment by Anaerin** [comment]
To decode that mess of JSON, here's the error that's being output on FreeBSD (When running undaemonized)
```
Uncaught Exception: AssertionError [ERR_ASSERTION]: File should always be initialied with stat
AssertionError [ERR_ASSERTION]: File should always be initialied with stat
    at /usr/local/games/minecraft/node_modules/fireworm/lib/file.js:45:7
    at FSReqCallback.oncomplete (fs.js:192:5)
About to exit with code 1
```
